# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  initialize:
    macos:
      xcode: "11.3.1"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: mkdir FuelMeDriver/support/Plist
      - run:
          name: Map GoogleService-Info-Production.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_PRODUCTION" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_PRODUCTION | base64 --decode -o FuelMeDriver/support/Plist/GoogleService-Info-Production.plist
      - run:
          name: Map GoogleService-Info-ProductionEnterprise.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_PRODUCTION_ENTERPRISE" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_PRODUCTION_ENTERPRISE | base64 --decode -o FuelMeDriver/support/Plist/GoogleService-Info-ProductionEnterprise.plist
      - run:
          name: Map GoogleService-Info-QA.plist
          command: |
            [ ! -z "$GOOGLE_SERVICE_INFO_PLIST_QA" ] 
            echo $GOOGLE_SERVICE_INFO_PLIST_QA | base64 --decode -o FuelMeDriver/support/Plist/GoogleService-Info-QA.plist
      - run: export SRCROOT=FuelMeDriver && FuelMeDriver/scripts/infoplist.sh 
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install gems
          command: bundle install --path circle_vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - circle_vendor/bundle
      - restore_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            if [ ! -d "Pods" ]
            then
               curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
              bundle exec pod install
            fi
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods
      - add_ssh_keys:
          fingerprints:
            - "{{ MATCH_GIT_SSH_FINGERPRINT }}"

  unit-tests:
    macos:
      xcode: "11.3.1"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - attach_workspace:
          at: .
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 5S (11.4) [" || true
      - run: bundle exec fastlane unit_tests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  upload-qa:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys: 
          fingerprints:
            - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build QA
          command: bundle exec fastlane qa
  upload-production-appstore:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys: 
            fingerprints:
              - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build Production
          command: bundle exec fastlane prod
  upload-production-enterprise:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys: 
            fingerprints:
              - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build Production Enterprise
          command: bundle exec fastlane prodenterprise
  building-tests-qa:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build QA
          command: bundle exec fastlane qa skipupload:true
  building-tests-prod:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build Production
          command: bundle exec fastlane prod skipupload:true
  building-tests-prodenterprise:
    macos:
      xcode: "11.3.1"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "<< MATCH_GIT_SSH_FINGERPRINT >>"
      - run:
          name: Build Production Enterprise
          command: bundle exec fastlane prodenterprise skipupload:true

workflows:
  version: 2
  build:
    jobs:
      - initialize
      - unit-tests:
          requires:
            - initialize
          filters:
            branches: 
              ignore:
                - develop
                - master
                - /release.*/
      - building-tests-qa:
          requires: 
            - initialize
          filters:
            branches: 
              ignore:
                - develop
                - master
                - /release.*/
      - building-tests-prod:
          requires: 
            - initialize
          filters:
            branches: 
              ignore:
                - develop
                - master
                - /release.*/
      - building-tests-prodenterprise:
          requires: 
            - initialize
          filters:
            branches: 
              ignore:
                - develop
                - master
                - /release.*/
      - upload-qa:
          requires: 
            - initialize
          filters:
            branches:
              only: 
                - develop
      - upload-production-appstore:
          requires: 
            - initialize
          filters:
            branches:
              only: 
                - /release.*/
      - upload-production-enterprise:
          requires: 
            - initialize
          filters:
            branches:
              only: 
                - /release.*/

